disabled_rules:
  - trailing_whitespace
included: # paths to include during linting. `--path` is ignored if present.
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  # - kitCommonDemoUITests
line_length: 200

class_delegate_protocol:
  severity: error

closure_parameter_position:
  severity: error

colon:
  severity: error

comma:
  severity: error

control_statement:
  severity: error

discouraged_direct_init:
  severity: error

empty_enum_arguments:
  severity: error

empty_parentheses_with_trailing_closure:
  severity: error

for_where:
  severity: error

implicit_getter:
  severity: error

legacy_constructor:
  severity: error

mark:
  severity: error

multiple_closures_with_trailing_closure:
  severity: error

notification_center_detachment:
  severity: error

opening_brace:
  severity: error

private_over_fileprivate:
  severity: error

redundant_discardable_let:
  severity: error

redundant_optional_initialization:
  severity: error

redundant_void_return:
  severity: error

syntactic_sugar:
  severity: error

todo:
  severity: error

trailing_newline:
  severity: error

unneeded_break_in_switch:
  severity: error

unused_closure_parameter:
  severity: error

unused_optional_binding:
  severity: error

vertical_parameter_alignment:
  severity: error

void_return:
  severity: error

xctfail_message:
  severity: error

function_parameter_count:
  warning: 13
  error: 15

type_name:
  min_length: 3
  max_length:
    warning: 60
    error: 70
  
file_length: 
  error: 600
  warning: 400

cyclomatic_complexity:
  warning: 14
  error: 15

#function_body_length:
#  warning: 55
#  error: 60

type_body_length:
  warning: 200

nesting:
  type_level:
    warning: 3
    error: 4
  statement_level:
    warning: 4
    error: 6

identifier_name:
  min_length: 2
  max_length:
    warning: 60
    error: 100
  excluded:
    - id
