# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def beers_libs
  pod 'NetworkPackage', :path => '../NetworkPackage'
end



target 'BeerListPDP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BeerListPDP
  beers_libs

  target 'BeerListPDPTests' do
    # Pods for testing
    beers_libs
  end

  target 'BeerListPDPUITests' do
    # Pods for testing
  end

end
