# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def third_party
  pod 'Kingfisher'
end

target 'CommonPackage' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CommonPackage
  third_party

  target 'CommonPackageTests' do
    # Pods for testing
    third_party
  end

end
